#!/usr/bin/env bash
# Displays the content of the file "/etc/passwd"
# Displays only 'username', 'user id', and 'home directory'

path="/etc/passwd"

while read -r line;
do
    echo "$line" | cut -d ':' -s -f 1,3,6
done < $path
