#!/usr/bin/env bash
# Displays the content of the file "/etc/passwd"
# Displays only 'username', 'user id', and 'home directory'

i=0
path="/etc/passwd"
file_content=$(cat $path)

while ((i < 10));
do
    echo "$file_content | cut -d ':' -f1,3,6"

    ((i++))
done
