#!/usr/bin/env bash
# Displays the content of the file "/etc/passwd"
# using while loop + IFS

path="/etc/passwd"

while IFS=: read -r USERNAME PASSWORD UID GID GECOS HOME SHELL;
do
    echo "The user $USERNAME is part of the $GID gang,\
    lives in $HOME and rides $SHELL.\
    $UID's place is protected by the passcode $PASSWORD,\
    more info about the user here: $GECOSD"
done