#!/usr/bin/env bash
# Displays the visitor IP along with the HTTP status code
# from the Apache log file

apache_log="./apache-access.log"

awk '{print $1, $9}' $apache_log | sort | uniq -c | sort -nr
