#!/usr/bin/env bash
# Displays numbers from 1 to 20 and
# displays "4" and then "bad luck from China" for the 4th iteration
# displays "9" and then "bad luck from Japan" for the 9th iteration
# displays "17" and then "bad luck from Ital"y for the 17th iteration

i=1

while ((i <= 20));
do
    case $i in
        4)
            echo "$i bad luck from China"
            ;;
        9)
            echo "$i bad luck from Japan"
            ;;
        17)
            echo "$i bad luck from Italy"
            ;;
        *)
            echo $i
            ;;
    esac

    ((i++))
done
