#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays "To infinity and beyond" indefinetely
# Displays "I hate the kill command" when receiving a SIGTERM signal
# Displays "Y U no love me?!" when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid when receiving a SIGQUIT or SIGTERM signal

touch /var/run/myscript.pid

pgrep -f "10-process_and_pid_file" > /var/run/myscript.pid

while true;
do
    echo "To infinity and beyond"
done

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid' SIGQUIT SIGTERM