#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinetely, with "sleep 2"
# in between each iteration, and "I am invincible!!!"  when receiving a
# SIGTERM signal
while true;
do
    echo "To infinity and beyond"
    sleep 2
done

trap 'echo "I am invincible!!!"' SIGTERM